name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest
 

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for DVC and potential commits

      # Step 2: Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 3: Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pre-commit pytest pytest-xdist dvc

      # Step 5: Run pre-commit hooks (Black & Flake8) - CI Fails If Formatting Is Wrong
      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
