name: Test

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Grant write access to the repository

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black pre-commit

      # Step 4: Auto-format code with Black
      - name: Run Black (auto-format)
        run: |
          black .

      # Step 5: Commit formatted changes (if any)
      - name: Commit formatted changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Auto-format code with Black [skip ci]"
            git push
            echo "Changes committed."
          fi

      # Step 6: Run Flake8 linter
      - name: Run Flake8
        run: |
          flake8 app.py

      # Step 7: Run pre-commit hooks
      - name: Run pre-commit hooks
        run: |
          pre-commit install
          pre-commit run --all-files --show-diff-on-failure || git diff --exit-code

      # Step 8: Commit pre-commit changes (if any)
      - name: Commit pre-commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Apply pre-commit fixes [skip ci]"
            git push
            echo "Changes committed."
          fi