name: Test

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black pre-commit

      - name: Run Black
        run: black --check --diff .

      - name: Run Flake8
        run: flake8 app.py

      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
