name : Test

on:
 push:
   branches: 
      -main

jobs:
  demo: 
    run-on: ubuntu-latest

  steps:
    name: Checkout repository
    uses: actions/checkout@v3


    name: setup pyhton
    uses: actions/setup-python@v2
    with:
       python-version : 3.10

    name : setup flake8
    run: |
          python -m pip install --upgrade pip
          pip install flake8

    name : run test
    run : |
          flake8 app.py

  



