name: Test

on:
  push:
    branches: 
      - main  # Fixed indentation and spacing

jobs:
  demo: 
    runs-on: ubuntu-latest  # Fixed "run-on" -> "runs-on"

    steps:
      - name: Checkout repository  # Each step must be in a list
        uses: actions/checkout@v3

      - name: Setup Python  # Step names should be properly formatted
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"  # YAML values should be inside quotes

      - name: Setup Flake8  # Proper indentation
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: flake8 app.py
